### ISSUE TITLE
Duplicate error message

### ISSUE THREAD

**Issue by pzinovkin** [joefitzgerald/builder-go#1]
<img width="461" alt="screenshot 2016-04-06 08 52 49" src="https://cloud.githubusercontent.com/assets/440630/14307166/acf3e5fc-fbd5-11e5-9af7-652aec955ec0.png">

Not so critical but would be nice to get rid of it. Maybe not to run test if build is failing.

**Comment by atombender** [comment]
I'd love to see this fixed. It's a bit annoying.
