### ISSUE TITLE
Not getting output unless I'm in the affected file

### ISSUE THREAD

**Issue by spbr** [joefitzgerald/builder-go#12]
So, maybe I'm misunderstanding something, but if I run go install . from the cmd line, I get this:

"
./server.go:68: not enough arguments in call to resources.HandleSubEvent
./server.go:118: cannot use resources.ReportsGetLast10 (type func(_data.Config, *sql.DB, *gocb.Bucket, *http.Request, http.ResponseWriter, map[string]string, *data.UserSession) string) as type definitions.FybioAPI in argument to managers.Auther
./server.go:123: cannot use resources.SubscribeUser (type func(_data.Config, _sql.DB, *gocb.Bucket, *http.Request, http.ResponseWriter, map[string]string, *data.UserSession) string) as type definitions.FybioAPI in argument to managers.Auther
./server.go:127: cannot use resources.UnsubscribeUser (type func(_data.Config, *sql.DB, *gocb.Bucket, *http.Request, http.ResponseWriter, map[string]string, *data.UserSession) string) as type definitions.FybioAPI in argument to managers.Auther
"

But I only see these errors when I save server.go in this example, not another file.  I thought it I would see errors from everywhere, no matter what file I'm in

**Comment by joefitzgerald** [comment]
You'll see it in the current package, not the current file. You won't see the error in another package.

**Comment by spbr** [comment]
Sorry, that makes perfect sense now.
